module.exports = [
    'JS - Developer workflow', 
    'JS - JavaScript on your machine',
    'JS - JavaScript foundations',
    'JS - Advanced functions',
    'JS - Project: Local library',
    'JS - Git and GitHub',
    'JS - Developer collaboration',
    'JS - Collaboration with GitHub',
    'JS - Testing basics',
    'JS - Error handling basics',
    'JS - Capstone: Decoder ring',
    'JS - Promises',
    'JS - Making requests',
    'JS - Modern asynchronous programming',
    'JS - Mock interview: Web requests',
    'JS - Careers: Networking',
];